### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Tonfast Mobile App
email: support@tonfast.com
description: Buy, Sell, or Rent anything in Ghana? TonFast.com has got you covered! Our free classified ads website offers a wide range of products and services, including mobile phones, cars, electronics, real estate, furniture, and even professional services. With TonFast.com, you can easily make money in Ghana by selling your pre-loved items or renting out your property. Join our platform today and discover the coolest way to trade online in Ghana!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://app.tonfast.com" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: tonfastgh
github_username:  tonfast
author: Tonfast LLC
logo: assets/images/large-logo.png
twitter:
  username: tonfastgh
social:
  name: Tonfast LLC
  links:
    - https://github.com/Tonfast

languages: ["en"]
ampdir: amp

github: https://github.com/Tonfast

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
